/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as SigmaRouteImport } from './routes/sigma'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as HuntRouteImport } from './routes/hunt'
import { Route as ForensicsRouteImport } from './routes/forensics'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as EntitiesIpRouteImport } from './routes/entities.$ip'

const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const SigmaRoute = SigmaRouteImport.update({
  id: '/sigma',
  path: '/sigma',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntRoute = HuntRouteImport.update({
  id: '/hunt',
  path: '/hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForensicsRoute = ForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIpRoute = EntitiesIpRouteImport.update({
  id: '/entities/$ip',
  path: '/entities/$ip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/capture': typeof CaptureRoute
  '/evidence': typeof EvidenceRoute
  '/fleet': typeof FleetRoute
  '/flows': typeof FlowsRoute
  '/forensics': typeof ForensicsRoute
  '/hunt': typeof HuntRoute
  '/lookup': typeof LookupRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/sigma': typeof SigmaRoute
  '/topology': typeof TopologyRoute
  '/entities/$ip': typeof EntitiesIpRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/capture': typeof CaptureRoute
  '/evidence': typeof EvidenceRoute
  '/fleet': typeof FleetRoute
  '/flows': typeof FlowsRoute
  '/forensics': typeof ForensicsRoute
  '/hunt': typeof HuntRoute
  '/lookup': typeof LookupRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/sigma': typeof SigmaRoute
  '/topology': typeof TopologyRoute
  '/entities/$ip': typeof EntitiesIpRoute
  '/entities': typeof EntitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/capture': typeof CaptureRoute
  '/evidence': typeof EvidenceRoute
  '/fleet': typeof FleetRoute
  '/flows': typeof FlowsRoute
  '/forensics': typeof ForensicsRoute
  '/hunt': typeof HuntRoute
  '/lookup': typeof LookupRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/sigma': typeof SigmaRoute
  '/topology': typeof TopologyRoute
  '/entities/$ip': typeof EntitiesIpRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/alerts'
    | '/capture'
    | '/evidence'
    | '/fleet'
    | '/flows'
    | '/forensics'
    | '/hunt'
    | '/lookup'
    | '/plugins'
    | '/settings'
    | '/sigma'
    | '/topology'
    | '/entities/$ip'
    | '/entities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/alerts'
    | '/capture'
    | '/evidence'
    | '/fleet'
    | '/flows'
    | '/forensics'
    | '/hunt'
    | '/lookup'
    | '/plugins'
    | '/settings'
    | '/sigma'
    | '/topology'
    | '/entities/$ip'
    | '/entities'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/alerts'
    | '/capture'
    | '/evidence'
    | '/fleet'
    | '/flows'
    | '/forensics'
    | '/hunt'
    | '/lookup'
    | '/plugins'
    | '/settings'
    | '/sigma'
    | '/topology'
    | '/entities/$ip'
    | '/entities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AlertsRoute: typeof AlertsRoute
  CaptureRoute: typeof CaptureRoute
  EvidenceRoute: typeof EvidenceRoute
  FleetRoute: typeof FleetRoute
  FlowsRoute: typeof FlowsRoute
  ForensicsRoute: typeof ForensicsRoute
  HuntRoute: typeof HuntRoute
  LookupRoute: typeof LookupRoute
  PluginsRoute: typeof PluginsRoute
  SettingsRoute: typeof SettingsRoute
  SigmaRoute: typeof SigmaRoute
  TopologyRoute: typeof TopologyRoute
  EntitiesIpRoute: typeof EntitiesIpRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigma': {
      id: '/sigma'
      path: '/sigma'
      fullPath: '/sigma'
      preLoaderRoute: typeof SigmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunt': {
      id: '/hunt'
      path: '/hunt'
      fullPath: '/hunt'
      preLoaderRoute: typeof HuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forensics': {
      id: '/forensics'
      path: '/forensics'
      fullPath: '/forensics'
      preLoaderRoute: typeof ForensicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$ip': {
      id: '/entities/$ip'
      path: '/entities/$ip'
      fullPath: '/entities/$ip'
      preLoaderRoute: typeof EntitiesIpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AlertsRoute: AlertsRoute,
  CaptureRoute: CaptureRoute,
  EvidenceRoute: EvidenceRoute,
  FleetRoute: FleetRoute,
  FlowsRoute: FlowsRoute,
  ForensicsRoute: ForensicsRoute,
  HuntRoute: HuntRoute,
  LookupRoute: LookupRoute,
  PluginsRoute: PluginsRoute,
  SettingsRoute: SettingsRoute,
  SigmaRoute: SigmaRoute,
  TopologyRoute: TopologyRoute,
  EntitiesIpRoute: EntitiesIpRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
