"""
Traffic monitoring and logging module.

Captures and logs all traffic generated by attack modules,
produces summary reports, and compares with Watchtower detection results.
"""

import json
import os
import time
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any, Dict, List

from traffic_testing.config import RESULTS_DIR, LOG_DIR


class TrafficMonitor:
    def __init__(self):
        self.session_id = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        self.start_time: float = 0
        self.end_time: float = 0
        self.attack_logs: Dict[str, List[dict]] = defaultdict(list)
        self.all_entries: List[dict] = []
        self.summary_path = os.path.join(RESULTS_DIR, f"summary_{self.session_id}.json")
        self.attack_summary_path = os.path.join(RESULTS_DIR, f"attack_summary_{self.session_id}.json")

    def start(self) -> None:
        self.start_time = time.time()
        print(f"\n{'='*70}")
        print(f"  WATCHTOWER TRAFFIC INJECTION TEST SUITE")
        print(f"  Session: {self.session_id}")
        print(f"  Started: {datetime.now(timezone.utc).isoformat()}")
        print(f"{'='*70}\n")

    def stop(self) -> None:
        self.end_time = time.time()
        self._load_attack_logs()
        self._write_summary()
        self._print_summary()

    def _load_attack_logs(self) -> None:
        for filename in os.listdir(LOG_DIR):
            if filename.endswith("_packets.jsonl"):
                attack_name = filename.replace("_packets.jsonl", "")
                filepath = os.path.join(LOG_DIR, filename)
                try:
                    with open(filepath, "r") as f:
                        for line in f:
                            line = line.strip()
                            if line:
                                entry = json.loads(line)
                                self.attack_logs[attack_name].append(entry)
                                self.all_entries.append(entry)
                except Exception:
                    pass

    def _write_summary(self) -> None:
        attack_stats = {}
        for attack_name, entries in sorted(self.attack_logs.items()):
            attack_stats[attack_name] = {
                "total_packets": len(entries),
                "first_packet": entries[0]["timestamp"] if entries else None,
                "last_packet": entries[-1]["timestamp"] if entries else None,
                "categories": list(set(e.get("attack", "").split("_")[0] for e in entries)),
                "protocols_used": list(set(e.get("protocol", "unknown") for e in entries)),
            }

        summary = {
            "session_id": self.session_id,
            "started_at": datetime.fromtimestamp(self.start_time, timezone.utc).isoformat(),
            "ended_at": datetime.fromtimestamp(self.end_time, timezone.utc).isoformat(),
            "duration_seconds": self.end_time - self.start_time,
            "total_packets_generated": len(self.all_entries),
            "unique_attacks": len(self.attack_logs),
            "attack_stats": attack_stats,
            "detectors_tested": self._get_expected_detections(),
            "protocol_coverage": list(set(e.get("protocol", "unknown") for e in self.all_entries)),
        }

        with open(self.summary_path, "w") as f:
            json.dump(summary, f, indent=2)
        print(f"\n  Summary written to: {self.summary_path}")

    def _get_expected_detections(self) -> list:
        return [
            {"attack": "tcp_connect_scan", "expected_detector": "recon.port_scan / stateful.host"},
            {"attack": "tcp_syn_scan", "expected_detector": "recon.port_scan / stateful.host"},
            {"attack": "horizontal_scan", "expected_detector": "recon.host_scan / stateful.host"},
            {"attack": "arp_poisoning", "expected_detector": "lan.trust (ARP binding conflict)"},
            {"attack": "c2_beacon_regular", "expected_detector": "behavior.beacon / stateful.host"},
            {"attack": "c2_beacon_no_response", "expected_detector": "behavior.beacon (response_anomaly)"},
            {"attack": "dns_tunneling", "expected_detector": "dns.tunnel"},
            {"attack": "dns_tunnel_txt", "expected_detector": "dns.tunnel (TXT queries)"},
            {"attack": "dga_domain_generation", "expected_detector": "dns.tunnel (entropy/labels)"},
            {"attack": "fast_flux_dns", "expected_detector": "dns.tunnel (subdomain count)"},
            {"attack": "ftp_credential_exposure", "expected_detector": "credential.ftp (PASS command)"},
            {"attack": "http_basic_auth_exposure", "expected_detector": "application.abuse (regex match)"},
            {"attack": "http_password_param", "expected_detector": "application.abuse (regex match)"},
            {"attack": "auth_failure_burst", "expected_detector": "application.abuse (auth.failure_burst)"},
            {"attack": "smb_brute_force", "expected_detector": "application.abuse (auth.failure_burst)"},
            {"attack": "dns_exfil_slow", "expected_detector": "dns.tunnel / exfil.volume_anomaly"},
            {"attack": "dns_exfil_fast", "expected_detector": "dns.tunnel (high query rate)"},
            {"attack": "http_exfil_fast", "expected_detector": "exfil.volume_anomaly / stateful.host"},
            {"attack": "icmp_exfil", "expected_detector": "application.abuse (icmp.tunnel.suspected)"},
            {"attack": "tls_protocol_mismatch", "expected_detector": "application.abuse (tls.protocol_mismatch)"},
            {"attack": "ssh_nonstandard_port", "expected_detector": "application.abuse (protocol.nonstandard_service)"},
            {"attack": "vnc_nonstandard_port", "expected_detector": "application.abuse (protocol.nonstandard_service)"},
            {"attack": "syn_flood_low_rate", "expected_detector": "recon.syn_flood / stateful.host"},
            {"attack": "modbus_unauthorized_write", "expected_detector": "iot-ot.safety (modbus write)"},
            {"attack": "mqtt_cleartext_creds", "expected_detector": "iot-ot.safety (mqtt creds)"},
            {"attack": "ssdp_discovery", "expected_detector": "discovery.parser"},
            {"attack": "mdns_discovery", "expected_detector": "discovery.parser"},
            {"attack": "nbns_discovery", "expected_detector": "nbns.parser"},
            {"attack": "lateral_admin_fanout", "expected_detector": "recon.lateral.admin_fanout / stateful.host"},
            {"attack": "ntlm_credential_exposure", "expected_detector": "ntlm.parser"},
            {"attack": "encrypted_c2_channel", "expected_detector": "behavior.beacon (with encryption)"},
            {"attack": "covert_icmp_channel", "expected_detector": "application.abuse (icmp.tunnel)"},
        ]

    def _print_summary(self) -> None:
        duration = self.end_time - self.start_time
        hours = int(duration // 3600)
        minutes = int((duration % 3600) // 60)
        seconds = int(duration % 60)

        print(f"\n{'='*70}")
        print(f"  TRAFFIC INJECTION TEST SUMMARY")
        print(f"{'='*70}")
        print(f"  Duration:    {hours}h {minutes}m {seconds}s")
        print(f"  Attacks:     {len(self.attack_logs)}")
        print(f"  Packets:     {len(self.all_entries)}")
        print(f"  Protocols:   {', '.join(sorted(set(e.get('protocol', '?') for e in self.all_entries)))}")
        print(f"{'='*70}")

        print(f"\n  {'Attack':<35} {'Packets':>8}  {'Protocols':<20}")
        print(f"  {'-'*35} {'-'*8}  {'-'*20}")
        for attack_name in sorted(self.attack_logs.keys()):
            entries = self.attack_logs[attack_name]
            protos = sorted(set(e.get("protocol", "?") for e in entries))
            print(f"  {attack_name:<35} {len(entries):>8}  {', '.join(protos):<20}")

        print(f"\n  EXPECTED DETECTIONS ({len(self._get_expected_detections())} tests):")
        print(f"  {'-'*65}")
        for det in self._get_expected_detections():
            print(f"  {det['attack']:<35} -> {det['expected_detector']}")

        print(f"\n  Next steps:")
        print(f"  1. Open Watchtower web dashboard and check Alerts")
        print(f"  2. Run: tower --cmd 'show alerts'")
        print(f"  3. Check: {self.summary_path}")
        print(f"  4. Compare generated traffic with detected alerts")
        print(f"  5. Run: python -m traffic_testing.compare_results")
        print(f"{'='*70}\n")


class AttackRunnerMonitor:
    def __init__(self, monitor: TrafficMonitor):
        self.monitor = monitor
        self.running_attacks: Dict[str, dict] = {}
        self.completed_attacks: Dict[str, dict] = {}

    def on_attack_start(self, attack_name: str, attack_obj: Any) -> None:
        self.running_attacks[attack_name] = {
            "start_time": time.time(),
            "attack_obj": attack_obj,
        }
        print(f"  [START] {attack_name}")

    def on_attack_complete(self, attack_name: str) -> None:
        if attack_name in self.running_attacks:
            info = self.running_attacks.pop(attack_name)
            elapsed = time.time() - info["start_time"]
            packets = info["attack_obj"].result.packets_sent if hasattr(info["attack_obj"], "result") else 0
            self.completed_attacks[attack_name] = {
                "elapsed_seconds": elapsed,
                "packets_sent": packets,
            }
            print(f"  [DONE]  {attack_name} ({packets} packets, {elapsed:.1f}s)")

    def on_attack_error(self, attack_name: str, error: str) -> None:
        print(f"  [ERROR] {attack_name}: {error}")
